### ISSUE TITLE
Wiring schematic needs updating

### ISSUE THREAD

**Issue by mnestor** [bikemike/IntexSpaManager#7]
A big thank you, been trying to figure this out for almost a year.

I got everything wired the way your schematic shows and it would just fritz out the Intex controller. Went back to the diagram from @UlrichMai and managed to get the D1 connected without causing issues with the Intex controller.

Pins I had to switch were: 2 and 5

Pin5: instead of going to D6 like in your schematic it went to Ground on the D1.
Pin2: This went to D6 instead of Ground.

**Comment by markusleben** [comment]
@mnestor Would you mind to share the correct wiring, I am a bit confused because the old files seems to be deleted.

**Comment by mnestor** [comment]
https://github.com/UlrichMai/MaiPureSpaController/blob/master/docs/schematics.png

There is the schematic that worked.

**Comment by markusleben** [comment]
Thanks!
