### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by markusleben** [bikemike/IntexSpaManager#8]
Thank you for sharing this app. I just installed platformio within vscode but I get some Errors. Is something wrong with the code or with my env?

` Executing task in folder IntexSpaManager-master: platformio run <

Processing SBH10 (platform: espressif8266; board: d1_mini; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.0.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 160MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100200.0 (10.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 40 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <PubSubClient> 2.8.0
|-- <WiFiManager> 0.16.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson> 6.18.0
|-- <OneWire> 2.3.5
|-- <DallasTemperature> 3.9.1
|   |-- <OneWire> 2.3.5
|-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPUpdateServer> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <LittleFS(esp8266)> 0.1.0
Building in release mode
THIS IS POST SCRIPT
Signing: src/OTAPublicKey.h

Running CMD: python3 ~/.platformio/packages/framework-arduinoespressif8266/tools/signing.py --mode header --publickey ~/projects/firmware_keys/public_intexspa.key --out src/OTAPublicKey.h

Compiling .pio/build/SBH10/src/SpaState.cpp.o
Compiling .pio/build/SBH10/src/main.cpp.o
Archiving .pio/build/SBH10/libae2/libWiFiManager.a
Archiving .pio/build/SBH10/libe76/libOneWire.a
Indexing .pio/build/SBH10/libae2/libWiFiManager.a
Indexing .pio/build/SBH10/libe76/libOneWire.a
Archiving .pio/build/SBH10/lib7b5/libDallasTemperature.a
Indexing .pio/build/SBH10/lib7b5/libDallasTemperature.a
Archiving .pio/build/SBH10/lib7f3/libESP8266mDNS.a
Indexing .pio/build/SBH10/lib7f3/libESP8266mDNS.a
Archiving .pio/build/SBH10/lib1e7/libArduinoOTA.a
Indexing .pio/build/SBH10/lib1e7/libArduinoOTA.a
Compiling .pio/build/SBH10/libac1/LittleFS/LittleFS.cpp.o
Compiling .pio/build/SBH10/libac1/LittleFS/lfs.c.o
Compiling .pio/build/SBH10/libac1/LittleFS/lfs_util.c.o
Archiving .pio/build/SBH10/libFrameworkArduinoVariant.a
Indexing .pio/build/SBH10/libFrameworkArduinoVariant.a
Compiling .pio/build/SBH10/FrameworkArduino/Crypto.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/Esp-frag.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/Esp-version.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/Esp.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/FS.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/FSnoop.cpp.o
Compiling .pio/build/SBH10/FrameworkArduino/FunctionalInterrupt.cpp.o
src/SpaState.cpp: In function 'void handleClockInterrupt()':
src/SpaState.cpp:33:29: warning: 'void SpaState::handleClockInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   33 |  state.handleClockInterrupt();
      |                             ^
In file included from src/SpaState.cpp:1:
src/SpaState.h:27:23: note: declared here
   27 |  ICACHE_RAM_ATTR void handleClockInterrupt();
      |                       ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp: In function 'void handleLatchInterrupt()':
src/SpaState.cpp:38:29: warning: 'void SpaState::handleLatchInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   38 |  state.handleLatchInterrupt();
      |                             ^
In file included from src/SpaState.cpp:1:
src/SpaState.h:28:23: note: declared here
   28 |  ICACHE_RAM_ATTR void handleLatchInterrupt();
      |                       ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp: In member function 'void SpaState::init(uint8_t, uint8_t, uint8_t, uint8_t)':
src/SpaState.cpp:57:53: warning: 'void handleClockInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   57 |  attachInterrupt(digitalPinToInterrupt(pinClock), ::handleClockInterrupt, RISING);
      |                                                     ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp:31:29: note: declared here
   31 | static void ICACHE_RAM_ATTR handleClockInterrupt()
      |                             ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp:57:81: warning: 'void handleClockInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   57 |  attachInterrupt(digitalPinToInterrupt(pinClock), ::handleClockInterrupt, RISING);
      |                                                                                 ^
src/SpaState.cpp:31:29: note: declared here
   31 | static void ICACHE_RAM_ATTR handleClockInterrupt()
      |                             ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp:58:53: warning: 'void handleLatchInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   58 |  attachInterrupt(digitalPinToInterrupt(pinLatch), ::handleLatchInterrupt, RISING);
      |                                                     ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp:36:29: note: declared here
   36 | static void ICACHE_RAM_ATTR handleLatchInterrupt()
      |                             ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp:58:81: warning: 'void handleLatchInterrupt()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   58 |  attachInterrupt(digitalPinToInterrupt(pinLatch), ::handleLatchInterrupt, RISING);
      |                                                                                 ^
src/SpaState.cpp:36:29: note: declared here
   36 | static void ICACHE_RAM_ATTR handleLatchInterrupt()
      |                             ^~~~~~~~~~~~~~~~~~~~
src/SpaState.cpp: In member function 'void SpaState::handleLatchInterrupt()':
src/SpaState.cpp:97:24: warning: 'void SpaState::ringBufferPush(uint16_t)' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   97 |   ringBufferPush(clkBuf);
      |                        ^
In file included from src/SpaState.cpp:1:
src/SpaState.h:275:23: note: declared here
  275 |  ICACHE_RAM_ATTR void ringBufferPush(uint16_t data)
      |                       ^~~~~~~~~~~~~~
src/SpaState.cpp:98:23: warning: 'bool SpaState::simulateButtonPress()' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   98 |   simulateButtonPress();
      |                       ^
In file included from src/SpaState.cpp:1:
src/SpaState.h:207:30: note: declared here
  207 |  inline ICACHE_RAM_ATTR bool simulateButtonPress();
      |                              ^~~~~~~~~~~~~~~~~~~
src/SpaState.cpp: In member function 'void SpaState::classifyTemperature()':
src/SpaState.cpp:302:5: error: use of an operand of type 'bool' in 'operator++' is forbidden in C++17
  302 |   ++blankCount;
      |     ^~~~~~~~~~
Compiling .pio/build/SBH10/FrameworkArduino/HardwareSerial.cpp.o
*** [.pio/build/SBH10/src/SpaState.cpp.o] Error 1
src/main.cpp: In function 'void checkWiFiConnection()':
src/main.cpp:199:12: warning: enumeration value 'WL_WRONG_PASSWORD' not handled in switch [-Wswitch]
  199 |     switch (newWiFiStatus)
      |            ^
src/main.cpp: In function 'void setupOTA()':
src/main.cpp:292:38: error: 'signing_pubkey' was not declared in this scope
  292 |  signPubKey = new BearSSL::PublicKey(signing_pubkey);
      |                                      ^~~~~~~~~~~~~~
*** [.pio/build/SBH10/src/main.cpp.o] Error 1
============================================================================================== [FAILED] Took 3.11 seconds ==============================================================================================

Environment    Status    Duration
-------------  --------  ------------
SBH10          FAILED    00:00:03.107
======================================================================================== 1 failed, 0 succeeded in 00:00:03.107 ========================================================================================
The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.`

**Comment by mnestor** [comment]
I got mine to compile by doing:

changed `bool blankCount = 0` to `int blankCount = 0` in SpaState.h

I also commented out all the signing stuff in main.cpp

```
 static void setupOTA()
 {
-       signPubKey = new BearSSL::PublicKey(signing_pubkey);
-       hash = new BearSSL::HashSHA256();
-       sign = new BearSSL::SigningVerifier(signPubKey);
-       Update.installSignature( hash, sign );
-
+       // signPubKey = new BearSSL::PublicKey(signing_pubkey);
+       // hash = new BearSSL::HashSHA256();
+       // sign = new BearSSL::SigningVerifier(signPubKey);
+       // Update.installSignature( hash, sign );
+
```

That looks like it would solve most of those errors.

**Comment by markusleben** [comment]
Thanks! It is compiling now.
